version: '3.8'

networks:
  store-network:

services:
  store-mysql:
    image: mysql:8.0
    container_name: store_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - store-network

  store-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store_app
    restart: always
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://store-mysql:3306/store
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - store-mysql
    networks:
      - store-network

volumes:
  db_data: