version: '3.8'

networks:
  notification-network:

services:
  notification-mysql:
    image: mysql:8.0
    container_name: notification_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notification
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - notification-network

  notification-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification_app
    restart: always
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://notification-mysql:3306/notification
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - notification-mysql
    networks:
      - notification-network

volumes:
  db_data: